"""Main constants of the project."""

from pathlib import Path

PROJECT_ROOT_PATH = Path(__file__).parents[1]

MATCH_PHOTOS = [
    {"name": "Agathe A", "photo": "data/Agathe Amadieu.jpg"},
    {"name": "Agathe M", "photo": "data/Agathe Minaro.jpg"},
    {"name": "Ambroise", "photo": "data/Ambroise de Tilière.jpg"},
    {"name": "Anna", "photo": "data/Anna Berger.JPG"},
    {"name": "Antoine G", "photo": "data/Antoine Grivot.jpg"},
    {"name": "Antoine T", "photo": "data/Antoine Toubhans.jpg"},
    {"name": "Arsène", "photo": "data/Arsène Tripard.jpg"},
    {"name": "Chloé", "photo": "data/Chloé Adnet.jpeg"},
    {"name": "Corentin", "photo": "data/Corentin Berteaux.jpg"},
    {"name": "Danilo", "photo": "data/Danilo Wictky Fabri.jpg"},
    {"name": "Edmond", "photo": "data/Edmond Verdier.jpg"},
    {"name": "Emeline", "photo": "data/Emeline Colomb.HEIC"},
    {"name": "Emilio", "photo": "data/Emilio De Sousa.jpg"},
    {"name": "Emmanuel", "photo": "data/Emmanuel Vignon.png"},
    {"name": "Erwan", "photo": "data/Erwan BENKARA.jpeg"},
    {"name": "Florent", "photo": "data/Florent Escribe.jpg"},
    {"name": "Gabriel", "photo": "data/Gabriel Guilabert.jpg"},
    {"name": "Gaspard", "photo": "data/Gaspard Sagot.jpg"},
    {"name": "Guillaume", "photo": "data/Guillaume DELEPOULLE.HEIC"},
    {"name": "Hafsa", "photo": "data/Hafsa Abid.jpg"},
    {"name": "Henry", "photo": "data/Henry Bichot.jpg"},
    {"name": "Hugo", "photo": "data/Hugo Khlaut.HEIC"},
    {"name": "Isaure", "photo": "data/Isaure de Fleurieu.jpg"},
    {"name": "Jad", "photo": "data/Jad Zarzour.jpg"},
    {"name": "Jean-Baptiste", "photo": "data/Jean-Baptiste Derycke.JPG"},
    {"name": "Jeanne Bac", "photo": "data/Jeanne Bachmann.jpeg"},
    {"name": "Jeanne Bau", "photo": "data/Jeanne Baudin.JPG"},
    {"name": "Jeremy", "photo": "data/Jeremy Desnoyer.jpg"},
    {"name": "Jérémy", "photo": "data/Jérémy Marchand.JPG"},
    {"name": "Julie", "photo": "data/Julie Prost.png"},
    {"name": "Julien", "photo": "data/Julien Perichon.png"},
    {"name": "Laurent", "photo": "data/Laurent Bonafons.jpg"},
    {"name": "Louis", "photo": "data/Louis Marx.jpg"},
    {"name": "Luca", "photo": "data/Luca Corrieri.jpeg"},
    {"name": "Lucas S", "photo": "data/Lucas Sor.jpeg"},
    {"name": "Lucas R", "photo": "data/Lucas Rinaldi.jpg"},
    {"name": "Maria", "photo": "data/Maria Vexlard.jpg"},
    {"name": "Mathieu", "photo": "data/Mathieu Soul.png"},
    {"name": "Max", "photo": "data/Max Perdrigeat.jpeg"},
    {"name": "Nicolas J", "photo": "data/Nicolas Jouron.jpg"},
    {"name": "Nicolas S", "photo": "data/Nicolas Saullet.jpg"},
    {"name": "Noé", "photo": "data/Noé Achache.png"},
    {"name": "Olivier", "photo": "data/Olivier Chatillon.jpg"},
    {"name": "Paul M", "photo": "data/Paul Monniot.jpg"},
    {"name": "Paul P", "photo": "data/Paul Pignal.png"},
    {"name": "Pauline", "photo": "data/Pauline Leopold.jpeg"},
    {"name": "Pierre", "photo": "data/Pierre Mérienne.jpg"},
    {"name": "Rayann", "photo": "data/Rayann Bentounes.jpg"},
    {"name": "Simon", "photo": "data/Simon Playe.jpeg"},
    {"name": "Tarek", "photo": "data/Tarek Ayed.jpg"},
    {"name": "Thomas", "photo": "data/Thomas Roulleaux Dugage.png"},
    {"name": "Vanina", "photo": "data/Vanina Cescato.jpeg"},
    {"name": "Vincent", "photo": "data/Vincent Zanetta.JPG"},
    {"name": "Yandi", "photo": "data/Yandi ANDRIA.HEIC"},
]